No PMIx server was reachable, but a PMI1/2 was detected.
If srun is being used to launch application,  2 singletons will be started.
[nid002516:1976016] shmem: mmap: an error occurred while determining whether or not /tmp/ompi.nid002516.105387/jf.0/3560112128/shared_mem_cuda_pool.nid002516 could be created.
[nid002516:1976016] create_and_attach: unable to create shared memory BTL coordinating structure :: size 134217728 
[nid003760:1436337] shmem: mmap: an error occurred while determining whether or not /tmp/ompi.nid003760.105387/jf.0/435093504/shared_mem_cuda_pool.nid003760 could be created.
[nid003760:1436337] create_and_attach: unable to create shared memory BTL coordinating structure :: size 134217728 
Process 0 global devices : [cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7)]
Process 0 local devices : [cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3)]
Traceback (most recent call last):
  File "/global/homes/s/seanjx/gigalens/testetc/nanolens.py", line 54, in <module>
    path = "output/"+now+"/"
           ~~~~~~~~~^~~~
TypeError: can only concatenate str (not "float") to str
/global/homes/s/seanjx/.conda/envs/gigajax/lib/python3.12/site-packages/mpi4jax/_src/decorators.py:60: UserWarning: Not using CUDA-enabled MPI. If you are sure that your MPI library is built with CUDA support, set MPI4JAX_USE_CUDA_MPI=1. To silence this warning, set MPI4JAX_USE_CUDA_MPI=0.
  warnings.warn(warn_msg)
2024-07-26 20:41:14.883942: E external/tsl/tsl/distributed_runtime/coordination/coordination_service_agent.cc:493] Failed to disconnect from coordination service with status: DEADLINE_EXCEEDED: Deadline Exceeded
Additional GRPC error information from remote target unknown_target_for_coordination_leader while calling /tensorflow.CoordinationService/ShutdownTask:
:UNKNOWN:Error received from peer  {grpc_message:"Deadline Exceeded", grpc_status:4, created_time:"2024-07-26T20:41:14.883742093-07:00"}
Proceeding with agent shutdown anyway. This is usually caused by an earlier error during execution. Check the logs (this task or the leader) for an earlier error to debug further.
Exception ignored in atexit callback: <function shutdown at 0x7f2429418040>
Traceback (most recent call last):
  File "/global/homes/s/seanjx/.conda/envs/gigajax/lib/python3.12/site-packages/jax/_src/distributed.py", line 205, in shutdown
    global_state.shutdown()
  File "/global/homes/s/seanjx/.conda/envs/gigajax/lib/python3.12/site-packages/jax/_src/distributed.py", line 108, in shutdown
    self.client.shutdown()
jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Deadline Exceeded
Additional GRPC error information from remote target unknown_target_for_coordination_leader while calling /tensorflow.CoordinationService/ShutdownTask:
:UNKNOWN:Error received from peer  {grpc_message:"Deadline Exceeded", grpc_status:4, created_time:"2024-07-26T20:41:14.883742093-07:00"}
2024-07-26 20:41:15.482791: E external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:1195] Shutdown barrier in coordination service has failed:
DEADLINE_EXCEEDED: Barrier timed out. Barrier_id: Shutdown::5187399502174675726. Timed out task names:
/job:jax_worker/replica:0/task:1
 [type.googleapis.com/tensorflow.CoordinationServiceError='']
This suggests that the workers are out of sync. Either at least one worker is too fast in its execution / crashed early or too slow / hanging. Check the logs for an earlier error to identify the root cause.
2024-07-26 20:41:15.482828: E external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:788] INTERNAL: Shutdown barrier has been passed with status: 'DEADLINE_EXCEEDED: Barrier timed out. Barrier_id: Shutdown::5187399502174675726. Timed out task names:
/job:jax_worker/replica:0/task:1
 [type.googleapis.com/tensorflow.CoordinationServiceError='']', but this task is not at the barrier yet. [type.googleapis.com/tensorflow.CoordinationServiceError='']
2024-07-26 20:41:15.482977: E external/tsl/tsl/distributed_runtime/coordination/coordination_service.cc:477] Stopping coordination service as shutdown barrier timed out. Check the task logs for an earlier error.
srun: error: nid002516: task 0: Exited with exit code 1
srun: Terminating StepId=28636924.0
2024-07-26 20:41:18.611319: W external/tsl/tsl/distributed_runtime/preemption/preemption_notifier.cc:89] SIGTERM caught at 2024-07-26T20:41:18.611264703-07:00
srun: error: nid003760: task 1: Killed
srun: Force Terminated StepId=28636924.0
